{
    "name": """Contrôle Accès Application Admin""",
    "summary": """Permet de configurer les administrateurs qui n'ont pas accès aux applications.""",
    "category": "Extra Tools",
    # "live_test_url": "",
    "images": ["images/banner.png"],
    "version": "14",
    "application": False,
    "author": "BMG Tech",
    "support": "",
    "website": "",
    "license": "Other OSI approved licence",  # MIT
    "depends": ["access_restricted"],
    "external_dependencies": {"python": [], "bin": []},
    "data": ["security/access_apps_security.xml", "security/ir.model.access.csv"],
    "demo": [],
    "qweb": [],
    "post_load": None,
    "pre_init_hook": None,
    "post_init_hook": None,
    "uninstall_hook": "uninstall_hook",
    "auto_install": False,
    "installable": True,
}
