# -*- coding: utf-8 -*-

{
    'name': 'Rapport Comptable Standard',
    'version': '14',
    'category': 'Accounting',
    'author': 'BMG Tech',
    'summary': 'Générer un rapport comptable dans Odoo Tree View, PDF et Excel, avec la nouvelle implémentation de la comptabilité',
    'website': '',
    'depends': ['account', 'report_xlsx'],
    'data': [
        'security/ir.model.access.csv',
        'data/report_paperformat.xml',
        'data/data_account_standard_report.xml',
        'data/res_currency_data.xml',
        'report/report_account_standard_report.xml',
        'views/account_view.xml',
        'views/account_standard.xml',
        'views/account_standard_report_template_view.xml',
        'views/res_currency_views.xml',
        'wizard/account_standard_report_view.xml',
    ],
    'demo': [],
    'license': 'AGPL-3',
    'support': 'https://github.com/fmdl',
    'installable': True,
    'auto_install': False,
    'price': 0.0,
    'currency': 'EUR',
}
